### ISSUE TITLE
Account History E2E Testing

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#315] opened 2021-05-30 18:38 UTC
#### What would you like to be added:

Currently, the test within Account History is very limited. It only checks the soundness of the RPC does not test it end to end with different setups. We need complete/full e2e testing on account history to prevent regression.

**Comment by ivan-zynesis** [comment] 2021-05-31 02:19
Duplicate of #292 ?

**Closed** 2021-05-31 03:29 UTC
Labels: area/jellyfish-api-core, kind/feature, triage/accepted
